### ISSUE TITLE
Can Jobtree be extended to the set of requirements for this

### ISSUE THREAD

**Issue by hannes-ucsc** [BD2KGenomics/slugflow#1]

**Comment by diekhans** [comment]
Note that one current issue with job tree is that it implements
one jobTree job as one cluster system job.  This is a big
limitation when the goal is to decompose into small jobs.
Currently only parasol is only scheduler that is fast enough to
really work with cactus.  If jobTree is select, it should be
modified to run multiple jobTree jobs per cluster system jobs;
or in this cases per VM instances.

**Comment by benedictpaten** [comment]
The answer is yes. I have a full write up to give you guys at the planning meeting. I estimate we'd have two write 500 lines of code (or less), to get a CWL to jobtree shim.
