### ISSUE TITLE
Evaluate Taverna

### ISSUE THREAD

**Issue by diekhans** [BD2KGenomics/slugflow#10]
http://www.biomedcentral.com/1471-2105/13/77

**Comment by hannes-ucsc** [comment]
http://www.taverna.org.uk/

**Comment by diekhans** [comment]
Far from being dead, Taverna is now an Apache Incubator project.

    http://taverna.incubator.apache.org/

It's huge, like really huge.  It might be good, it might be big a train wreak.  It would be a large amount of work to even figure this out.  It has no special support for clouds or the spot market.  Standard virtual cluster stuff.

It vastly exceeds our needs and we should not invest in it.
