### ISSUE TITLE
Use jobStore.getPublicUrl() to publish user script

### ISSUE THREAD

**Issue by hannes-ucsc** [BD2KGenomics/slugflow#105]
In the master process, use the job store to generate a public URL to the user script. Pass that URL and the MD5 of the user script to the batch system's constructor.

In the Mesos backend, add the URL and MD5 to the task info.

**Comment by hannes-ucsc** [comment]
Depends on #104

**Comment by cket** [comment]
There is a problem with this plan. The jobStore is created after and depends on the batch system because of the batch system's additional config modifications, so we can't easily make the batch system dependent on the jobStore.

**Comment by hannes-ucsc** [comment]
I'm taking this for now. Didn't get around to doing it today, though. Got distracted pairing with Clayton.

**Comment by hannes-ucsc** [comment]
e539b4e81bcebe0e621ec5b0b112bcfc72b1ada0
