### ISSUE TITLE
Investigate occasionally hung unit tests

### ISSUE THREAD

**Issue by hannes-ucsc** [BD2KGenomics/slugflow#111]
See http://jenkins.cgcloud.info/job/jobtree/34/

**Comment by cket** [comment]
abstractBatchSystemTest.MesosBatchSystemTest.testGetIssuedJobIDs reveals a race condition in our mesos batch system method. This test issues jobs, then immediately calls getIssuedJobIds, then finishes and the teardown method is called. The tear down method calls mesosbatchsystem.teardown, which calls driver.stop(), and then joins and does joins on the driver thread. However, looking at the mesos source code reveals that the driver stop method will be ignored if it's status is not RUNNING or ABORTED. Once the stop is ignored, tear down continues on to join(), with blocks indefinitely. 

This is supported by the fact that driver.stop(), if not ignored, calls schedProcess.stop(), which logs("Asked to shutdown framework..."). In the faulty case, we never see this logging message. 

I recommend changing our driver.stop() to driver.abort() to avoid this, and insure that the framework is always stopped.

**Comment by hannes-ucsc** [comment]
I think this one did it: 

https://github.com/BD2KGenomics/jobTree/commit/5432568b59257070035f2d4fb4483fa87f4a49e4
