### ISSUE TITLE
Evaluate JobTree

### ISSUE THREAD

**Issue by jvivian** [BD2KGenomics/slugflow#12]

**Comment by hannes-ucsc** [comment]
Pro: Dynamic job creation
Pro: Encapsulates all code of a distributed workload in a single, self-contained class
Pro: Supports multiple batch backends
Pro: In-house expertise
Pro: Community adoption
Con: Relies on shared file system (?)
Con: Does not model disk space as a requirement (?)
Con: DAG to jobTree transform is not straight forward and introduces artificial dependencies
Con: Doesn't feel like a good fit for massively parallel but simple, cookie cutter  workloads
