### ISSUE TITLE
AWSJobStore: Add a variant of _uploadStream  that does not use multipart uploads ...

### ISSUE THREAD

**Issue by hannes-ucsc** [BD2KGenomics/slugflow#122]
... if the payload doesn't warrant it. 

MP uploads require at least three requests. We should test the size of the input if we can and use the simple PUT request if it is smaller than a single part.

**Comment by cket** [comment]
I am trying to  implement this by adding another, non-multipart, private reader() method in _uploadStream but there is a complication. There is a key.set_contents_from_stream method that I'm using, but when I test it Boto complains that S3 does not support chunked file transfer. Why would there be a streaming upload method then?

**Comment by cket** [comment]
There is a similar variant already in place for _upload()

**Comment by cket** [comment]
As Hannes suggested, using key.set_contents_from_file with a StringIO object fixed the problem. Closed via https://github.com/BD2KGenomics/jobTree/commit/f91155d81b49cf4141455ccd72cef18ac15bdf10
