### ISSUE TITLE
Evaluate Mesos (1/2)

### ISSUE THREAD

**Issue by jvivian** [BD2KGenomics/slugflow#14]

**Comment by hannes-ucsc** [comment]
Pro: The resource offer approach is novel and compelling
Con: Master-ful design, but multi-master supported
Pro: Soft-state, master can rebuild its state from a running cluster (bold claim that needs to be verified) 
Pro: Multi-language
Con: Setup probably complicated
Con: Tests have only run up to 100 real nodes (emulated 50000 but I think that has to be taken with a grain of salt)
Pro: web UI for viewing cluster state

Need to figure out how to match JobTree backend API and Mesos' Scheduler API.
