### ISSUE TITLE
Adapt Mutect pipeline to DAG API

### ISSUE THREAD

**Issue by hannes-ucsc** [BD2KGenomics/slugflow#142]

**Comment by jvivian** [comment]
Porting the complete GATK pipeline with all of the pre-processing steps.   Currently a work in progress but am committing to our slugflow repo: https://github.com/BD2KGenomics/slugflow/tree/master/gatk-pipeline

Testing a subset of quick pre-processing targets before implementing the lengthier ones as a sanity check.
