### ISSUE TITLE
Decide on new name for jobTree

### ISSUE THREAD

**Issue by hannes-ucsc** [BD2KGenomics/slugflow#145]

**Comment by jvivian** [comment]
Musa was taken, but nobody has taken:   **µSA**    
Obscurity through ascii characters!

**Comment by jvivian** [comment]
K40 -- the radioactive isotope found in bananas. one github project with k40 in the name.

Mauz -- arabic word for Musa/Banana. no github projects.

**Branchia** -- a shortening of "Heterobranchia"  which is the clade for banana slug.  "Branchia" has "branch" in it (like a tree) and there are no github/code projects for it.

**Comment by hannes-ucsc** [comment]
+1 for Branchia if you can tell me how to pronounce the ch in it. Like the
x in Latex?

"µ" typically gets ascii-fied as "u" which would render "usa" ... just
sayin'

On Thu, Jul 9, 2015 at 11:39 AM, John Vivian <notifications@github.com>
wrote:

> K40 -- the radioactive isotope found in bananas. one github project with
> k40 in the name.
>
> Mauz -- arabic word for Musa/Banana. no github projects.
>
> *Branchia* -- a shortening of "Heterobranchia" which is the clade for
> banana slug. "Branchia" has "branch" in it (like a tree) and there are no
> github/code projects for it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BD2KGenomics/slugflow/issues/145#issuecomment-120099885>
> .
>



-- 
Hannes Schmidt
Software Engineer
Center for Biomolecular Science and Engineering
University of California, Santa Cruz

(206) 696-2316 (cell)
hannes@ucsc.edu

**Comment by cket** [comment]
Phloem - "the vascular tissue in plants that conducts sugars and other metabolic products downward from the leaves." Pronounced flow-em.  Only 3 tiny github repos with this name, none of which are starred. Most recent commit on any was 2 months ago.  Maybe an alternate spelling would make it completely unique.

**Comment by jvivian** [comment]
Could spell it: Floam -- google shows it used to be an old crappy child's toy and there's no github repos.

Branchia is pronounced with the 'ch' as a 'k' sound (Bron-Kia).
