### ISSUE TITLE
Evaluate Mesos (2/2)

### ISSUE THREAD

**Issue by jvivian** [BD2KGenomics/slugflow#15]

**Comment by cket** [comment]
Mesos is installed on every node in the cluster, with masters and slaves. The slaves report their resource use (CPU, Memory, Storage, etc) to the master, which offers those resources to the scheduler so each slave is utilized as efficiently as possible, and each slave can run multiple tasks simultaneously. It is fault tolerant, supports elastic clusters, and offers Java, Python, and C APIs. Any scheduler we use with Mesos would have to be modified, although it shouldn’t be anything too extensive. I think it is strong contender.
