### ISSUE TITLE
awsJobStore fails on sortTest with test errors enabled

### ISSUE THREAD

**Issue by cket** [BD2KGenomics/slugflow#153]

**Comment by cket** [comment]
With success_ratio set to 1, awsSortTest succeeds. Set to anything else, the job store fails when trying to retry a failed job. The job fails with a test failure, sends back its log file, the job is retried, and the job tries to clear the already existing log file.  However, it cannot find this file and throws an exception.

**Comment by benedictpaten** [comment]
I thought delete file function silent succeeds, even if the file is not
present? Is that not in the docs?

**Comment by cket** [comment]
You're right - whoops. This behavior was already in place for delete, but not for deleteFile. This is fixed, and sortTest is now passing.
