### ISSUE TITLE
Containerize: picard-tools

### ISSUE THREAD

**Issue by jvivian** [BD2KGenomics/slugflow#161]

**Comment by jvivian** [comment]
Robert uses Version 1.104 but it's easiest to install via `apt-get install picard-tools` so don't worry about the version too much (but please record what version is downloaded, likely 1.105).

**Comment by AashJ** [comment]
picard-tools added to github

**Comment by jvivian** [comment]
**DOCKERFILE**

1. There needs to be an `ENTRYPOINT`
2. There needs to be a **/data** folder and the final `WORKDIR` must be set to it. 

**MAKEFILE**
 
2. When I ran `man picard-tools` in the container (after installing `man`), I got Version 1.95.

**Comment by jvivian** [comment]
I needed this for a script I'm writing so I pushed an image I could grab to DockerHub
