### ISSUE TITLE
Containerize: Ubu

### ISSUE THREAD

**Issue by jvivian** [BD2KGenomics/slugflow#164]

**Comment by jvivian** [comment]
[Ubu]( https://github.com/mozack/ubu/downloads )

This should be easy, base JAVA image and you should be done.  Please containerize this particular jar: **ubu-1.2-jar-with-dependencies.jar**

**Comment by AashJ** [comment]
Ubu dockerfile and makefile uploaded to ubu branch on github.

**Comment by jvivian** [comment]
Missing **/data** and `WORKDIR` set to it.

**Comment by AashJ** [comment]
Added /data directory.
