### ISSUE TITLE
Evaluate SLURM elastic (2/2)

### ISSUE THREAD

**Issue by cket** [BD2KGenomics/slugflow#19]

**Comment by cket** [comment]
Slurm is very large (500,000 lines of code) and the documentation is lacking. The Elastic Slurm documentation I can find is 2 years out of date, and Slurm as a whole is primarily designed to run on a static cluster rather than an environment like EC2 spot market. I don't think this is the way to go.

**Comment by hannes-ucsc** [comment]
I agree, I found an official FAQ entry describing how someone uses EC2 with slurm. They create a cluster of a predefined size and then seed /etc/hosts with the IPs of all slaves. No dynamic instance allocation, no spot market.

http://slurm.schedmd.com/faq.html#amazon_ec2

**Comment by benedictpaten** [comment]
Right - so this could be a subroutine for managing a given fixed set of
machines, but does not solve the general spot market problem.
