### ISSUE TITLE
Are there other tools that already fulfill our requirements

### ISSUE THREAD

**Issue by hannes-ucsc** [BD2KGenomics/slugflow#2]

**Comment by jvivian** [comment]
CJ found the following:
MakeFlow -- http://ccl.cse.nd.edu/software/makeflow/

**Comment by hannes-ucsc** [comment]
Ideally, we should have stumbled upon ClusterK in the research for this issue.  If we didn't, either they are not advertising themselves correctly or we are using the wrong search terms.

**Comment by jvivian** [comment]
Broken up into different tasks. Closing.

**Comment by macieksmuga** [comment]
Perhaps create a label ("investigate competing tool"?) to mark and group all the resulting sub-tasks.
