### ISSUE TITLE
Test Parallelization Speed

### ISSUE THREAD

**Issue by jvivian** [BD2KGenomics/slugflow#21]
Answer this question:  On an 8 core machine, is it faster to parallelize 2 tasks by assigning them 4 cores each or is the same as if they were each assigned 8?

**Comment by jvivian** [comment]
I'm also testing which commands benefit from parallelism despite the fact that the programs are multithreaded and (generally) saturate all of the cores they are working on.

**Comment by diekhans** [comment]
John Vivian <notifications@github.com> writes:
> Answer this question: On an 8 core machine, is it faster to parallelize 2 tasks
> by assigning them 4 cores each or is the same as if they were each assigned 8?

In general, it hugely depends on the behavior of the tasks.

For bioinformatics applications, we just tend to not worry about
it.  Often file I/O is the killer anyway, so optimizing CPU
isn't as important.  Spending tons of time trying to get a 5%
optimization isn't worth the effort.  Just buy/rent another computer.

**Comment by jvivian** [comment]
Test complete -- no real difference.
