### ISSUE TITLE
Look at AWS autoscaling

### ISSUE THREAD

**Issue by hannes-ucsc** [BD2KGenomics/slugflow#24]

**Comment by cket** [comment]
Pros: 
-Stats collection as part of cloud watch
-We can create custom cloud watch metrics, and auto scaling uses cloud watch metrics as 'triggers' for scaling up or down, but I haven't seen an explicit answer whether custom metrics can be used as triggers. If we can, we could potentially publish task queue lengths as 'triggers'
-Preexisting metrics for resource utilization
-spot market support
-existing instances can be added to auto scaling group

Cons:
-Only one instance type per auto scaling group. 
-Triggers might be too simplistic. They are in the form of "If (metric), scale up/down x percent/instances". An example of a problem this causes: there are separate metrics for CPU and memory, so if we were using 100% CPU but our memory is below the set trigger point, the memory trigger would scale the cluster down.

**Comment by hannes-ucsc** [comment]
Good summary.
