### ISSUE TITLE
Convert GATK bash script to jobTree script

### ISSUE THREAD

**Issue by hannes-ucsc** [BD2KGenomics/slugflow#26]

**Comment by jvivian** [comment]
Ask Hannes for best method to handle try/excepts with a retry to handle intermittent network errors:  http://pastebin.com/QdA7fWUT

http://stackoverflow.com/questions/2083987/how-to-retry-after-exception-in-python

**Comment by jvivian** [comment]
Sucessfully ran as a jobTree in a single node on ec2

**Comment by jvivian** [comment]
Test get_intermediate_path() for large files (5Gb and 11Gb). 

Ensure that download of large files does not have the same complications as uploading large files.

**Comment by jvivian** [comment]
Downloading large files (5-12Gb) did not require multipart downloading.  Test ran to completion.
