### ISSUE TITLE
Create JobStore abstraction

### ISSUE THREAD

**Issue by hannes-ucsc** [BD2KGenomics/slugflow#27]

**Comment by hannes-ucsc** [comment]
I've thought about this a little more.  It feels odd to track individual tasks as  objects in an object store.  Secondly, S3 is only eventually consistent. So you only get the A and D from ACID with S3. You don't care about the I since you are trying to manipulate single objects only, not multiple objects in a transaction.  

I suggest splitting this task in two. One: refactor job file tracking into its own class. And two implement that interface on an ACD compliant persistence engine, like SimpleDB.

**Comment by benedictpaten** [comment]
This is now done, bar adding in support for globalTempDir. I am trying to add this too, so that once the jobStore is implemented in AWS the whole system will work.

**Comment by hannes-ucsc** [comment]
I'm assuming this includes the abstraction and the shared FS implementation?

On Thu, Apr 23, 2015 at 9:16 AM, Benedict Paten <notifications@github.com>
wrote:

> This is now done, bar adding in support for globalTempDir. I am trying to
> add this too, so that once the jobStore is implemented in AWS the whole
> system will work.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BD2KGenomics/slugflow/issues/27#issuecomment-95637383>
> .
>



-- 
Hannes Schmidt
Software Engineer
Center for Biomolecular Science and Engineering
University of California, Santa Cruz

(206) 696-2316 (cell)
hannes@ucsc.edu

**Comment by benedictpaten** [comment]
This is "done" - though we need to merge the pull request I just made. I'm going to talk to john.  When it's done I'll start developing on the bd2k fork.
