### ISSUE TITLE
Setup single-node Mesos cluster

### ISSUE THREAD

**Issue by hannes-ucsc** [BD2KGenomics/slugflow#29]

**Comment by jvivian** [comment]
Setup on EC2
**Mesos_Test_Node**

### Go to build dir
    cd ~/mesos-0.22.0/build

### Start master
     ./bin/mesos-master.sh --work_dir=/tmp/mesos 

### Start slave 
    ./bin/mesos-slave.sh --master=<IP from above>:5050

### Test framework (requires "make check")
    ./src/examples/java/test-framework <IP>:5050
