### ISSUE TITLE
Improve jobTree unit tests

### ISSUE THREAD

**Issue by hannes-ucsc** [BD2KGenomics/slugflow#41]
Eliminate the auto detection of the BS

**Comment by benedictpaten** [comment]
I have started doing this by refactoring the organisation of the unit tests to make it clearer what's what.

**Comment by benedictpaten** [comment]
This is too big an issue. I think we should can this issue and make smaller issues - like writing tests for the jobStore and batchSystem interfaces.

**Comment by hannes-ucsc** [comment]
I wrote job store and john is writing a batch system test. We should close this and create more specific tasks as John suggests.

**Comment by hannes-ucsc** [comment]
The batch system test is tracked as #59
