### ISSUE TITLE
Prototype DAG to jobTree conversion (2 of 3)

### ISSUE THREAD

**Issue by hannes-ucsc** [BD2KGenomics/slugflow#42]

**Comment by jvivian** [comment]
I've settled on a preliminary data structure (DiGraph in the networkx package) and have implemented the first part of the algorithm.

tests and source are being worked on here: https://github.com/jvivian/SlugFlow/tree/master/Dag2Tree

**Comment by jvivian** [comment]
I've completed the 2nd part of the algorithm and am working on collapsing the pseudonodes.
![diagram](http://i.imgur.com/eEg3qHI.png)
![graph](http://i.imgur.com/HJTOgyr.png)

**Comment by jvivian** [comment]
Algorithm is finished -- will need to go through it with Benedict at some point to determine its inefficiencies and how it can be implemented better.  Currently building complex and difficult structures to test edge cases.

![pc](http://i.imgur.com/cBno5LW.png)
