### ISSUE TITLE
Rewrite jobtree_gatk for use with new FileJobStore implementation

### ISSUE THREAD

**Issue by jvivian** [BD2KGenomics/slugflow#48]

**Comment by jvivian** [comment]
I am not able to open Issues with the forked version of jobTree, but I am getting errors when trying to run the development+mesos branch.

I have my pythonpath set correctly, but am getting the following:

    Traceback (most recent call last):
      File "jobTree_HelloWorld.py", line 8, in <module>
        from jobTree.scriptTree.target import Target
    ImportError: No module named scriptTree.target

    make all

make all appears to work

    make test

[Jvivian@eduroam-169-233-202-159:~/Dropbox/School/PhD/Projects/JT/jobTree]$ make test
#Running python allTests.py
PYTHONPATH=.. PATH=../../bin:$PATH python allTests.py --testLength=SHORT
Traceback (most recent call last):
  File "allTests.py", line 25, in <module>
    from jobTree.test.src.jobTest import TestCase as jobTest
  File "/Users/Jvivian/Dropbox/School/PhD/Projects/JT/jobTree/test/src/jobTest.py", line 14, in <module>
    from jobTree.src.stack import Stack
  File "/Users/Jvivian/Dropbox/School/PhD/Projects/JT/jobTree/src/stack.py", line 44, in <module>
    from jobTree.src.master import mainLoop
  File "/Users/Jvivian/Dropbox/School/PhD/Projects/JT/jobTree/src/master.py", line 45, in <module>
    from sonLib.bioio import logger, getTotalCpuTime, logStream, system
ImportError: cannot import name logStream
make: *** [test] Error 1

**Comment by benedictpaten** [comment]
That's because I reorganised the module structure. scriptTree is gone, it's
now just in src, e.g.

from jobTree.src.target import Target

not

from jobTree.scriptTree.target import Target

**Comment by jvivian** [comment]
Ah, my mistake -- Thank you Benedict! Hope you start feeling better soon.

**Comment by hannes-ucsc** [comment]
But what about the

ImportError: cannot import name logStream

Do you have unpushed changes to sonLib, Benedict?

On Wed, Apr 29, 2015 at 10:35 AM, John Vivian <notifications@github.com>
wrote:

> Ah, my mistake -- Thank you Benedict! Hope you start feeling better soon.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BD2KGenomics/slugflow/issues/48#issuecomment-97513765>
> .
>



-- 
Hannes Schmidt
Software Engineer
Center for Biomolecular Science and Engineering
University of California, Santa Cruz

(206) 696-2316 (cell)
hannes@ucsc.edu

**Comment by jvivian** [comment]
Ya, that is still an issue I am getting.

**Comment by hannes-ucsc** [comment]
CJ ran into it yesterday and was going to ask Benedict that question I just
asked. Don't know if he did, though.

On Wed, Apr 29, 2015 at 10:37 AM, John Vivian <notifications@github.com>
wrote:

> Ya, that is still an issue I am getting.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BD2KGenomics/slugflow/issues/48#issuecomment-97514208>
> .
>



-- 
Hannes Schmidt
Software Engineer
Center for Biomolecular Science and Engineering
University of California, Santa Cruz

(206) 696-2316 (cell)
hannes@ucsc.edu

**Comment by jvivian** [comment]
I got my [HelloWorld script](https://github.com/jvivian/10k_exome_project/blob/fileStore_Implemenation/JTree/jobTree_HelloWorld.py) working using the fileStoreID system -- I tried passing Target to the class to make the empty IDs but it didn't work so I just used the class to create placeholder variables. 

I had to use getEmptyFileStoreID() and updateGlobalFile(), which seems redundant if they are happening in the same target function, because I got errors when attempting to use writeGlobalFile():    (line 89 in fileJobStore.py)

    if not os.path.isdir(jobStoreID):
      raise RuntimeError("Path %s is not a dir" % jobStoreID)

I believe this is because the arguments from writeGlobalFile in target.py are mixed up:

    return self.jobStore.writeFile(localFileName, self.job.jobStoreID)

File "../jobTree_HelloWorld.py", line 57, in hello_world_child
  hw.bar_bam = target.writeGlobalFile('bar_bam.txt')
File "../src/target.py", line 102, in writeGlobalFile
  return self.jobStore.writeFile(localFileName, self.job.jobStoreID)
File "../fileJobStore.py", line 89, in writeFile
  raise RuntimeError("Path %s is not a dir" % jobStoreID)
RuntimeError: Path bar_bam.txt is not a dir

**Comment by hannes-ucsc** [comment]
On Wed, Apr 29, 2015 at 12:21 PM, John Vivian <notifications@github.com>
wrote:

> I got my HelloWorld script
> <https://github.com/jvivian/10k_exome_project/blob/fileStore_Implemenation/JTree/jobTree_HelloWorld.py>
> working using the fileStoreID system -- I tried passing Target to the class
> to make the empty IDs but it didn't work so I just used the class to create
> placeholder variables.
>
Don't understand why passing a Target instance (instance, not the class
itself!!!) doesn't work. Do you have a instance of the Target class
available when calling the constructor of the class that is supposed to
hold the job store IDs?

>  I had to use getEmptyFileStoreID() and updateGlobalFile(), which seems
> redundant if they are happening in the same target function, because I got
> errors when attempting to use writeGlobalFile(): (line 89 in
> fileJobStore.py)
>
Looks like an obvious bug that you could fix. We don't use pull requests so
remember to pull before making changes to avoid conflicts when pushing.


> if not os.path.isdir(jobStoreID):
>   raise RuntimeError("Path %s is not a dir" % jobStoreID)
>
> I believe this is because the arguments from writeGlobalFile in target.py
> are mixed up:
>
> return self.jobStore.writeFile(localFileName, self.job.jobStoreID)
>
> File "../jobTree_HelloWorld.py", line 57, in hello_world_child
> hw.bar_bam = target.writeGlobalFile('bar_bam.txt')
> File "../src/target.py", line 102, in writeGlobalFile
> return self.jobStore.writeFile(localFileName, self.job.jobStoreID)
> File "../fileJobStore.py", line 89, in writeFile
> raise RuntimeError("Path %s is not a dir" % jobStoreID)
> RuntimeError: Path bar_bam.txt is not a dir
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BD2KGenomics/slugflow/issues/48#issuecomment-97549869>
> .
>



-- 
Hannes Schmidt
Software Engineer
Center for Biomolecular Science and Engineering
University of California, Santa Cruz

(206) 696-2316 (cell)
hannes@ucsc.edu

**Comment by jvivian** [comment]
Pushed a fix to: **development+mesos**

**Comment by jvivian** [comment]
An issue that may have not been considered that I'll bring up during the scrum is:

How does the FileStoreID system handle files that need to be in the same directory but are not called by path explicitly?  The GATK pipeline (unfortunately) makes use of this in almost every tool/step/target.

**Comment by jvivian** [comment]
Reporting in case it's a bug and not an intended feature (I'm pretty sure it's intended) --  FileStoreIDs that point to the SAME local file generate 2 differently named (but duplicate) files.

**Comment by jvivian** [comment]
Got all the bugs worked out.  running now in with --stats to test out jobTreeStats functionality.

**Comment by jvivian** [comment]
Ran on 2 different samples. Saved results from jobTreeStats.   

Will bring up allocating memory for a jobtree target when the memory usage for a tool is variable by input size.
