### ISSUE TITLE
Fix possible false success

### ISSUE THREAD

**Issue by hannes-ucsc** [BD2KGenomics/slugflow#56]
1) Create reproduction
2) Step through with Benedict

**Comment by cket** [comment]
This doesn't appear to be a false success, but possibly unnecessarily  re-running successful commands. All the expected output is produced, but we get this warning "Despite the batch system claiming failure the job /private/var/folders/m7/btdp90xs6t9g42chx7m8kwfw0000gn/T/tmpiBoNqq/jobTree/jobs/t3/t0 seems  to have finished and been removed". 

The full log contents are here
http://pastebin.com/YCi1qC4T 

The parent job is added to active, the child t3/t0 (for example) is added and finished successfully. It is then added to active, and its follow on is run. In this case the follow on is failed once before completing. The parent job is added to active again, and all the child commands are re-run and we get above warning.
