### ISSUE TITLE
Create Containers for Workflow Tools

### ISSUE THREAD

**Issue by jvivian** [BD2KGenomics/slugflow#61]
Samtools
PicardTools
MuTect
SomaticSniper
VarScan
Pindel

**Comment by jvivian** [comment]
[x] samtools
[x] picardtools
[x] mutect
[ ] SomaticSniper
[ ] VarScan
[ ] Pindel
https://registry.hub.docker.com/repos/jvivian/

**Comment by hannes-ucsc** [comment]
Isn't Ashish working on this?

**Comment by jvivian** [comment]
yes, Aashish is working on that but I couldn't assign him the ticket on
waffle and I figured the job still falls under my purview.

**Comment by hannes-ucsc** [comment]
Should be broken up and assigned between John and  Aashish..

**Comment by jvivian** [comment]
I am closing this ticket and opening several more.
