### ISSUE TITLE
Rewrite jobTree pipeline to use Containers

### ISSUE THREAD

**Issue by jvivian** [BD2KGenomics/slugflow#62]
Given that the BAMs we are from the Broad and are pre-processed:

1. Download T/N
2. Index T/N (samtools)
3. Create index/dict for reference (picardtools)
4. Create .VCF (Mutect)

**Comment by jvivian** [comment]
Finished pipeline, runs to completion. 
Differs from the pre-processed VCF result by -1 True Positive, +1 False Positive. Did not change balanced accuracy (88%) more than +- 1 percent.

Working on refactoring, adding TODOs when I get time to do code review with Hannes. 
https://github.com/jvivian/SlugFlow/blob/master/jobTree_dockerPipeline/jobtree_docker_pipeline.py

**Comment by benedictpaten** [comment]
That is probably due to non-determinism of algorithms.

**Comment by jvivian** [comment]
Need to schedule code review with Hannes.

**Comment by hannes-ucsc** [comment]
Continued in #75
