### ISSUE TITLE
Research availability of cluster scheduler for EC2

### ISSUE THREAD

**Issue by hannes-ucsc** [BD2KGenomics/slugflow#7]

**Comment by jvivian** [comment]
https://github.com/danilop/SampleBatchProcessing
2 Step Process using Boto and the AWS CLI. 
SendJobs:
Jobs are packaged as JSONs into SQS messages and files in the local directory are uploaded to a specified S3 Folder.  SendJobs accepts 6 inputs when called:  local dir, S3 bucket, S3 input prefix, S3 output, SQS queue, and AWS region.
GetJobs:
Jobs are pulled from Queue then run via subprocess.  GetJobs takes in arguments that specify the commands to be run on that set of jobs and things like output extension. 

Doesn't look like anything is setup for spot market or resumability.

**Comment by jvivian** [comment]
http://star.mit.edu/cluster/docs/latest/overview.html
https://github.com/jtriley/StarCluster
MIT's StarCluster
Built on top of the Sun Grid scheduler --  may be useful in setting up the clusters that that will be used for each step.   You create a cluster (which appears painless) then log in as the master of a cluster which gives you the ability to send jobs to worker nodes.  There's options to use the spot market as well.   It looks like you can then use  Sun Grid (qsub) to submit jobs.  Amazon recommends StarCluster by name when using spot pricing to do scientific computing on the cheap: http://aws.amazon.com/ec2/purchasing-options/spot-instances/spot-and-science/

I'm still searching through the user guide but I'm having trouble finding information on how it deals with interruption of those spot instances.

**Comment by cket** [comment]
https://github.com/mesosphere/cloudformation-mesos 
Sets up cloud formation autoscaling groups of Mesos masters and slaves. Doesn't mention Spot Market, but seems compatible.
