### ISSUE TITLE
Find reason for slow rate of offers

### ISSUE THREAD

**Issue by hannes-ucsc** [BD2KGenomics/slugflow#74]

**Comment by cket** [comment]
The rate of resource offers seems to be determined by the mesos master and slaves, without any way to configure it.

**Comment by hannes-ucsc** [comment]
Ask on the mailing list.

**Comment by hannes-ucsc** [comment]
http://www.mail-archive.com/user@mesos.apache.org/msg03569.html

**Comment by cket** [comment]
The allocation_interval flag does what we want. I set it to 250ms and didn't see any of the pauses in the program that we had seen before when the framework was waiting for offers.

**Comment by hannes-ucsc** [comment]
Aha! 

I'd mention that on the mailing list. Just to be polite and help others running into the same issue.

**Comment by hannes-ucsc** [comment]
Did we ever add this parameter to our unit tests?

**Comment by hannes-ucsc** [comment]
CJ, can you use  MesosTestSupport for Mesos tests.

**Comment by hannes-ucsc** [comment]
Fixed by c814b715ffde69f52f588bf6cdba5dc59ba374d8
