### ISSUE TITLE
Prototype stats collection for CPU and memory

### ISSUE THREAD

**Issue by hannes-ucsc** [BD2KGenomics/slugflow#77]
The ultimate goal is to determine whether we are use resources efficiently

**Comment by cket** [comment]
I am using psutil (https://pypi.python.org/pypi/psutil) to collect cpu/mem usage percentages on slaves and send them back to the master, who currently just logs them. We could put these into stats files, which could then be graphed. The only problem right now is that this introduces an external dependency

**Comment by hannes-ucsc** [comment]
I think I am ok with the foreign dependency. With Mesos we already introduced a foreign dependency so this isn't even a first. We should offer a way to install jobTree without Mesos. "Extras" seem to be the way to do that:

https://pythonhosted.org/setuptools/setuptools.html#declaring-extras-optional-features-with-their-own-dependencies
