### ISSUE TITLE
Create MakeFlow for GATK

### ISSUE THREAD

**Issue by jvivian** [BD2KGenomics/slugflow#8]

**Comment by diekhans** [comment]
btw, any file system based pipeline should use atomic file
creation to ensure that incomplete results don't get mistake for
completed ones.

Extremely simple and makes a huge difference.

**Comment by jvivian** [comment]
Created: https://github.com/jvivian/10k_exome_project/blob/master/Code/MakeFlow_Tests/Makeflow

Since the provided EC2 support for things like Work_Queue don't seem to work anymore, we *could* use MakeFlow but we'd have to write our own python wrapper to orchestrate the WQ system's "workers" with spot priced instances.   MakeFlow keeps a log of what things succeeded so resumability is actually pretty great (and could include things like downloading, uploading to S3), but that means the MakeFlow file would have to originate from the Master which means either generating a MakeFlow file for all 10k pairs, or have one MakeFlow file that runs 10k jobs (seems a bit insane).
