### ISSUE TITLE
Hot deployment of jobTree and user script

### ISSUE THREAD

**Issue by hannes-ucsc** [BD2KGenomics/slugflow#83]

**Comment by hannes-ucsc** [comment]
Every Mesos task will carry a number of (URL,hash) tuples. We'll call these tuples "static dependencies" or SD for short. There will be one SD for the user script and optionally another one for the jobTree source distribution, sdist in setuptools parlance. The executor will download the files pointed at by the URL and install them in a place where they are discoverable by the command run for each task. The hash will be an MD5 allowing the executor to quickly determine if it has the desired version of that file.

TBD: Whose responsibility will the SD distribution be? It overlaps with the batch system (since the Mesos scheduler  will populate task data with these SDs) but the job store seems like a more appropriate place for this functionality. The FileJobStore would generate file:// URLs while the AWS job store would generate HTTP URLs pointing at a publicly accessible S3 bucket.

TBD: What do we use to download the URLs on the executor side? I've had a good experience with libcurl and the Python bindings for it. The advantage is that libcurl supports FTP and HTTP(S) out of the box. The disadvantage is that it *probably* isn't thread-safe.

TBD: How do we handle the case where jobTree is updated but the running executor originates to the previously installed version? Should the executor just terminate itself, relying on the Mesos worker to rerun it?

TBD: How do we handle multiple in-flight tasks that have contradictory SD hashes? We don't want to end up repeatedly downloading and reinstalling jobTree. Maybe this won't be an issue but we should at least detect and log it.

**Comment by cket** [comment]
PycURL is a python binding for lib curl that is thread safe so we can use that:
http://pycurl.sourceforge.net

**Comment by hannes-ucsc** [comment]
That's the one I use in s3am. Interestingly, it does not satisfy a strict definition of thread-safety because that one cannot share a handle between threads. It should be fine for our purposes as long as you obey the one-handle-per-thread rule.

**Comment by hannes-ucsc** [comment]
To prototype this, use

https://docs.python.org/2/library/simplehttpserver.html

and urllib2 on the executor.

**Comment by cket** [comment]
I am considering making the "static dependency" tuples part of the JobTreeJob class- this way, the data is already unpicked at the proper place in the executor, and seems to fit naturally with the rest of the class. The class describes the job, and part of the job is which script defines it.

**Comment by hannes-ucsc** [comment]
The batch system doesn't control Job instantiation, the job stores do, and one of them, AWSJobStore already subclasses Job for it's own purposes. I'm afraid you'll have to resort to aggregation instead of inheritance here, i.e. wrap each Job instance in a MesosJob instance. There is even a name for this pattern: decorator.

https://en.wikipedia.org/wiki/Decorator_pattern

**Comment by hannes-ucsc** [comment]
I've changed my mind. Let's not run an HTTP server in the master process. We need to utilize the jobStore. Anything else would be silly.

**Comment by hannes-ucsc** [comment]
Depends on #104

**Comment by hannes-ucsc** [comment]
Depends on #105

**Comment by hannes-ucsc** [comment]
Depends on #106

**Comment by cket** [comment]
Follow up in #167 and #154
