### ISSUE TITLE
Make mesos master and slave run as non-privileged user

### ISSUE THREAD

**Issue by hannes-ucsc** [BD2KGenomics/slugflow#94]

**Comment by cket** [comment]
This is done, with the exception of logging. Spark logs to /var/logs, and I am trying to imitate that but I am getting permission denied errors because /var/ and its children can only be modified by root. I am looking into how spark box gets around this.

**Comment by hannes-ucsc** [comment]
The Mesos logs should got into a subdirectory of /var/log, i.e. /var/log/mesos. After creating that directory, run `chgrp mesosbox /var/log/mesos && chmod g+w /var/log/mesos`. That should do it.

We also need to put the Mesos log files onto instance storage (ephemeral volume) if available. SparkBox does that already by "bind-mounting". /mnt/ephemeral/var/log/sparkbox into /var/log/sparkbox. I'm pretty happy with that approach since bind mounting gives you the ease of use of symbolic links with the opaqueness of hard links. Feel free to replicate that behavior as part of this issue or punt to another ticket.
