### ISSUE TITLE
MesosBatchSystem fails testIssuedJob

### ISSUE THREAD

**Issue by jvivian** [BD2KGenomics/slugflow#96]

**Comment by jvivian** [comment]
To replicate error run unittests in MesosBatchSystemTest.   
Mesos is actively queueing the command, but it doesn't ever get executed.  

1. DEBUG:jobTree.batchSystems.mesos:Queueing the job command: touch /var/folders/ys/lvrh99s90rl887jb11cxqc9h0000gn/T/tmpOQeIHl/test.txt with job id: 0 ...
2. DEBUG:jobTree.batchSystems.mesos:... queued

The job then reaches the state: **TASK_LOST** and the executor is terminated

1. DEBUG:jobTree.batchSystems.mesos:Task 0 is in a state TASK_LOST
2. WARNING:jobTree.batchSystems.mesos:Task 0 is in unexpected state TASK_LOST with message 'Executor terminated'

**Comment by cket** [comment]
I replicated this error, but once I marked jobTree/src as source in pycharm all the tests passed again.

**Comment by cket** [comment]
I also ran 'make test'  and the tests succeeded, so I think we are ok.

**Comment by jvivian** [comment]
I removed and recloned jobTree, ran **python setup.py install --user**, and made sure jobTree/src was set as an additional source in pycharm and I'm getting import errors when running **make test**, **jobSort**, and still failing on **testIssueJob** for Mesos so it seems to be some sort of issue on my end.

If you or Hannes have any suggestions let me know, otherwise I'll work it out when I'm back later this week -- feel free to close this ticket if you can't replicate any of the issues I'm having.

**Comment by hannes-ucsc** [comment]
You shouldn't have to

*python setup.py install --user*

It may even cause problems. Ultimately, the goal of your "make jobTree
pip-installable" is to enable developers to run "python setup.py develop"
but for now that should not be necessary. You should be able to simple
checkout the project and run "make test" to run the tests. If you get
import errors while doing that, I recommend cleaning your python
installation. Run "pip list" to see what is installed and can be
uninstalled.

On Mon, Jun 1, 2015 at 1:06 PM, John Vivian <notifications@github.com>
wrote:

> I removed and recloned jobTree, ran *python setup.py install --user*, and
> made sure jobTree/src was set as an additional source in pycharm and I'm
> getting import errors when running *make test*, *jobSort*, and still
> failing on *testIssueJob* for Mesos so it seems to be some sort of issue
> on my end.
>
> If you or Hannes have any suggestions let me know, otherwise I'll work it
> out when I'm back later this week -- feel free to close this ticket if you
> can't replicate any of the issues I'm having.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BD2KGenomics/slugflow/issues/96#issuecomment-107692071>
> .
>



-- 
Hannes Schmidt
Software Engineer
Center for Biomolecular Science and Engineering
University of California, Santa Cruz

(206) 696-2316 (cell)
hannes@ucsc.edu

**Comment by hannes-ucsc** [comment]
Try again with the latest commit on master (cf74c25635f7363e256e27090b99cd5eaf64e7cf)

**Comment by hannes-ucsc** [comment]
Closing as irreproducible.
